apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
  app: mysql-tracker
spec:
 hostname: mysql
 containers:
 - name: mysql
   image: mysql:5.7
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: password
   - name: MYSQL_DATABASE
     value: trainer
   - name: MYSQL_USER
     value: trainer_user
   - name: MYSQL_PASSWORD
     value: trainer_pass
   ports:
   - containerPort: 3306
 - name: tracker-docker
   image: abrams88/tracker-docker-img
   ports:
   - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mysql-service
 labels:
  app: mysql-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 8080
   protocol: TCP
 selector:
  app: mysql-tracker
